#!/usr/bin/env bash
# Ralph Wiggum Loop Runner
# Iterative fresh-context agent loop for GitHub Copilot CLI
#
# Usage: bash run-loop.sh [OPTIONS]
# See SKILL.md for full documentation.

set -euo pipefail

# ──────────────────────────────────────────────
# Defaults
# ──────────────────────────────────────────────
MAX_ITERATIONS=20
TIMEOUT_MINUTES=10
CONFIG_FILE="./LOOP_CONFIG.md"
AGENT="ralph-wiggum-loop"
DRY_RUN=false
AUTO_REVIEW=0  # 0 = disabled
TASKS_FILE="./TASKS.md"
PROGRESS_FILE="./PROGRESS.md"
LOG_DIR="./.loop-logs"

# ──────────────────────────────────────────────
# Parse arguments
# ──────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --max-iterations) MAX_ITERATIONS="$2"; shift 2 ;;
    --timeout)        TIMEOUT_MINUTES="$2"; shift 2 ;;
    --config)         CONFIG_FILE="$2"; shift 2 ;;
    --agent)          AGENT="$2"; shift 2 ;;
    --dry-run)        DRY_RUN=true; shift ;;
    --auto-review)    AUTO_REVIEW="$2"; shift 2 ;;
    --tasks)          TASKS_FILE="$2"; shift 2 ;;
    --progress)       PROGRESS_FILE="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: run-loop.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --max-iterations N   Maximum iterations (default: 20)"
      echo "  --timeout M          Per-iteration timeout in minutes (default: 10)"
      echo "  --config PATH        Path to LOOP_CONFIG.md (default: ./LOOP_CONFIG.md)"
      echo "  --agent AGENT        Agent to use (default: ralph-wiggum-loop)"
      echo "  --dry-run            Preview without executing"
      echo "  --auto-review N      Run reviewer every N iterations (0=disabled)"
      echo "  --tasks PATH         Path to TASKS.md (default: ./TASKS.md)"
      echo "  --progress PATH      Path to PROGRESS.md (default: ./PROGRESS.md)"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ──────────────────────────────────────────────
# Load config overrides from LOOP_CONFIG.md
# ──────────────────────────────────────────────
load_config() {
  if [[ -f "$CONFIG_FILE" ]]; then
    local val
    val=$(grep -oP '(?<=max_iterations:\s)\d+' "$CONFIG_FILE" 2>/dev/null || true)
    [[ -n "$val" ]] && MAX_ITERATIONS="$val"
    val=$(grep -oP '(?<=timeout_minutes:\s)\d+' "$CONFIG_FILE" 2>/dev/null || true)
    [[ -n "$val" ]] && TIMEOUT_MINUTES="$val"
    val=$(grep -oP '(?<=auto_review_interval:\s)\d+' "$CONFIG_FILE" 2>/dev/null || true)
    [[ -n "$val" ]] && AUTO_REVIEW="$val"
  fi
}

# ──────────────────────────────────────────────
# Preflight checks
# ──────────────────────────────────────────────
preflight() {
  if ! command -v copilot &>/dev/null; then
    echo "❌ Error: 'copilot' CLI not found. Install GitHub Copilot CLI first."
    exit 1
  fi

  if [[ ! -f "$TASKS_FILE" ]]; then
    echo "❌ Error: $TASKS_FILE not found. Create a task list first."
    echo "   Tip: Use the loop-planner agent or copy from templates/TASKS.md"
    exit 1
  fi

  if [[ ! -f "$PROGRESS_FILE" ]]; then
    echo "📝 Creating $PROGRESS_FILE..."
    cat > "$PROGRESS_FILE" << 'EOF'
# Progress Log

> Auto-generated by Ralph Wiggum Loop Runner

EOF
  fi

  mkdir -p "$LOG_DIR"
}

# ──────────────────────────────────────────────
# Check if all tasks are complete
# ──────────────────────────────────────────────
all_tasks_complete() {
  if ! grep -qP '^\s*-\s*\[ \]' "$TASKS_FILE" 2>/dev/null && \
     ! grep -qP '^\s*-\s*\[~\]' "$TASKS_FILE" 2>/dev/null && \
     ! grep -qP '^\s*-\s*\[!\]' "$TASKS_FILE" 2>/dev/null; then
    return 0
  fi
  return 1
}

# ──────────────────────────────────────────────
# Detect oscillation (same error 3+ times)
# ──────────────────────────────────────────────
detect_oscillation() {
  local recent_errors
  recent_errors=$(grep -c '❌ Failed' "$PROGRESS_FILE" 2>/dev/null || echo 0)

  if [[ "$recent_errors" -ge 3 ]]; then
    # Check if last 3 failures mention the same task
    local last_three
    last_three=$(grep -B1 '❌ Failed' "$PROGRESS_FILE" | grep 'Task:' | tail -3 | sort -u | wc -l)
    if [[ "$last_three" -le 1 ]]; then
      return 0  # Oscillation detected
    fi
  fi
  return 1
}

# ──────────────────────────────────────────────
# Check for STOP flag
# ──────────────────────────────────────────────
check_stop_flag() {
  if grep -q '\[STOP\]' "$TASKS_FILE" 2>/dev/null; then
    return 0
  fi
  if [[ -f ".loop-stop" ]]; then
    return 0
  fi
  return 1
}

# ──────────────────────────────────────────────
# Build the iteration prompt
# ──────────────────────────────────────────────
build_prompt() {
  local iteration="$1"
  cat << EOF
You are executing iteration $iteration of a Ralph Wiggum Loop.

Read the following files to understand current state:
- $TASKS_FILE — your task list (find the next [ ] or [!] task)
- $PROGRESS_FILE — history of previous iterations

Instructions:
1. Read both files completely
2. Find the NEXT pending task (marked [ ]) or retry a failed task (marked [!])
3. Execute ONLY that one task
4. Update $TASKS_FILE to mark the task [x] (done) or [!] (failed)
5. Append an iteration entry to $PROGRESS_FILE with results
6. If all tasks are [x], add a final "All tasks complete" entry

Remember: ONE task only. Fresh context. State lives in files.
EOF
}

# ──────────────────────────────────────────────
# Run one iteration
# ──────────────────────────────────────────────
run_iteration() {
  local iteration="$1"
  local prompt
  prompt=$(build_prompt "$iteration")
  local log_file="$LOG_DIR/iteration-${iteration}.log"

  echo "🔄 Iteration $iteration / $MAX_ITERATIONS"
  echo "   Agent: $AGENT"
  echo "   Log: $log_file"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "   [DRY RUN] Would execute copilot with prompt:"
    echo "   $prompt" | head -5
    echo "   ..."
    return 0
  fi

  # Run copilot with timeout, fresh context each time
  if timeout "${TIMEOUT_MINUTES}m" copilot \
    --agent="$AGENT" \
    --prompt "$prompt" \
    --allow-all \
    2>&1 | tee "$log_file"; then
    echo "   ✅ Iteration $iteration complete"
  else
    local exit_code=$?
    if [[ $exit_code -eq 124 ]]; then
      echo "   ⏰ Iteration $iteration timed out after ${TIMEOUT_MINUTES}m"
      echo "## Iteration $iteration — $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$PROGRESS_FILE"
      echo "**Status:** ⏰ Timed out" >> "$PROGRESS_FILE"
      echo "" >> "$PROGRESS_FILE"
    else
      echo "   ⚠️ Iteration $iteration exited with code $exit_code"
    fi
  fi
}

# ──────────────────────────────────────────────
# Run the review agent
# ──────────────────────────────────────────────
run_review() {
  local iteration="$1"
  echo ""
  echo "🔍 Running loop reviewer (after iteration $iteration)..."

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "   [DRY RUN] Would run loop-reviewer agent"
    return 0
  fi

  copilot \
    --agent="loop-reviewer" \
    --prompt "Review the Ralph Wiggum Loop health. Read PROGRESS.md and TASKS.md, then provide a health report." \
    --allow-all \
    2>&1 | tee "$LOG_DIR/review-after-${iteration}.log"
}

# ──────────────────────────────────────────────
# Main loop
# ──────────────────────────────────────────────
main() {
  echo "╔══════════════════════════════════════════╗"
  echo "║     🚌 Ralph Wiggum Loop Runner 🚌      ║"
  echo "║     \"I'm in danger!\" — Ralph Wiggum     ║"
  echo "╚══════════════════════════════════════════╝"
  echo ""

  load_config
  preflight

  echo "Configuration:"
  echo "  Max iterations:  $MAX_ITERATIONS"
  echo "  Timeout:         ${TIMEOUT_MINUTES}m per iteration"
  echo "  Agent:           $AGENT"
  echo "  Tasks:           $TASKS_FILE"
  echo "  Progress:        $PROGRESS_FILE"
  echo "  Auto-review:     $([ "$AUTO_REVIEW" -gt 0 ] && echo "every $AUTO_REVIEW iterations" || echo "disabled")"
  echo "  Dry run:         $DRY_RUN"
  echo ""

  local iteration=0
  local start_time
  start_time=$(date +%s)

  while [[ $iteration -lt $MAX_ITERATIONS ]]; do
    iteration=$((iteration + 1))

    # ── Stop condition checks ──
    if all_tasks_complete; then
      echo ""
      echo "🎉 All tasks complete! Loop finished after $((iteration - 1)) iterations."
      break
    fi

    if detect_oscillation; then
      echo ""
      echo "🔄 Oscillation detected! Same task failing 3+ consecutive times."
      echo "   Stopping loop. Review PROGRESS.md for details."
      break
    fi

    if check_stop_flag; then
      echo ""
      echo "🛑 Stop flag detected. Halting loop."
      break
    fi

    # ── Run iteration ──
    echo ""
    run_iteration "$iteration"

    # ── Auto-review check ──
    if [[ "$AUTO_REVIEW" -gt 0 ]] && [[ $((iteration % AUTO_REVIEW)) -eq 0 ]]; then
      run_review "$iteration"
    fi

    # Brief pause between iterations for filesystem sync
    sleep 2
  done

  # ── Summary ──
  local end_time
  end_time=$(date +%s)
  local elapsed=$(( end_time - start_time ))
  local minutes=$(( elapsed / 60 ))
  local seconds=$(( elapsed % 60 ))

  echo ""
  echo "════════════════════════════════════════════"
  echo "Loop Summary"
  echo "  Iterations run: $iteration"
  echo "  Total time:     ${minutes}m ${seconds}s"
  echo "  Logs:           $LOG_DIR/"
  echo "════════════════════════════════════════════"

  # Final review if we completed
  if [[ "$AUTO_REVIEW" -gt 0 ]] && [[ "$DRY_RUN" != "true" ]]; then
    echo ""
    echo "Running final review..."
    run_review "final"
  fi
}

main "$@"
